version: '3'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nextjs:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`example.com`)"
      - "traefik.http.routers.nextjs.entrypoints=web"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  scraper:
    build: .
    command: npm run start:scraper
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - nextjs